server.port=5000

spring.datasource.url=jdbc:postgresql://localhost:5432/cerka_dev
spring.datasource.username=postgres
spring.datasource.password=6500
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jackson.property-naming-strategy=SNAKE_CASE